keys:
  - &mini-nas ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFxk3SUTMe8de1v8ultvy4cR7N5/Rs4Q8ozX4nl6kOwA
  - &steamdeck_willy ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
  - &thenixbeast_will ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - age:
        - *mini-nas
        - *steamdeck_willy
        - *thenixbeast_will
  - path_regex: modules/distributed_builders/secrets.yaml
    key_groups:
    - age:
        - *mini-nas
        - *steamdeck_willy
        - *thenixbeast_will
stores:
  yaml:
    indent: 2
