keys:
  - &manjaro_will age1g4nm9uphc70e30zluas6hghdpcl76gr8nluhnuq680clv2g8vgts3cke0z
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - age: 
        - *manjaro_will
      #pgp:
      #  - *other_person

# Note: Be sure to not include a - before subsequent key types under key_groups (i.e. age in the above example should not have a - in front). This will otherwise cause sops to require multiple keys (shamir secret sharing) to decrypt a secret, which breaks normal sops-nix usage.
